sudo: false
language: objective-c
osx_image: xcode8

script:
- swift package generate-xcodeproj --enable-code-coverage
- xcodebuild -project Runner.xcodeproj -scheme Runner test

after_success:
- bash <(curl -s https://codecov.io/bash)